export const GENDER = {
  MASCULINO: "MASCULINO",
  FEMININO: "FEMININO",
  OUTROS: "OUTROS",
};

export const STATUS_PHASE = {
  FINALIZADA: "FINALIZADA",
  NAO_FINALIZADA: "NAO_FINALIZADA",
};

export const STATUS_SECTION = {
  DERROTA: "DERROTA",
  VITORIA: "VITORIA",
  DESISTENCIA: "DESISTENCIA",
};
